### ISSUE TITLE
VRMspringbone and PhysicsAsset

### ISSUE THREAD

**Issue by Zongiin** [ruyo/VRM4U#11]
Sorry, I don't know where to ask this question so I ask here. I see your video here (https://youtu.be/ohuoVnCEX5k) and I see that my character's hair in my project acts like the one on the left in game but acts like the right in Physics Asset editor. I imported with "No Physics Asset" unchecked so I don't know why it works like that. I want the hair physics to work like the right one. Sorry I am quite new to UE4 and cannot read japanese.

**Comment by ruyo** [comment]
Hi.
Thanks for the question. It use VRMSpringBone node in AnimBlueprint. See
https://youtu.be/Qlz0bUSLjss?t=413

If you are using SkeletalMeshActor or Pawn, it will work with PhysicsAsset instead of VRMSpringBone.
If you are using BP_VrmCharacterBase or VRMSamplePawn, it will work with VRMSpringBone automatically.

Thanks!

**Comment by Zongiin** [comment]
Thank you for the explanation, I think I understand now.
