### ISSUE TITLE
triggered assertion failure while packaging `runtimeload` map in `CitySample` demo project

### ISSUE THREAD

**Issue by Dutchi-Who** [ruyo/VRM4U#296]
**Describe the bug**
Hi ruyo,

I'm recently testing with the city sample map (UE5 demo map) and trying to add a vrm import feature to the game. However this crash happens when I'm trying to import the vrm file. 

![image](https://github.com/ruyo/VRM4U/assets/96360144/9d3f4bee-8171-40ae-8d63-cd085dc3f265)
 
After doing some detail research on this issue I found maybe it's something related with the game thread conflicted with the city sample map. Do you know if is there any possible solutions on this crash? Thanks!

![image](https://github.com/ruyo/VRM4U/assets/96360144/c693bad8-2d34-446b-a333-68edabc87f8f)

**UnrealEngine Version:**
UE 5.2.1

**Comment by ruyo** [comment]
Hi.
As far as I have tested, it works fine in the City sample.
Please check if the VRM file you are using can be read properly or check the works with other viewers or importers.
You will also need the entire log to investigate. Please attach a text file.
However, I expect that the problem is on the model side this time, so there may be limitations in investigating from the logs.

**Comment by Dutchi-Who** [comment]
Thank you ruyo. I have fixed it for now. The issue is that I packaged the project in development mode, when `CitySample` overridden some Mipmap settings in its C++ file with a `WITH_EDITOR` macro.
