### ISSUE TITLE
VRM4U Plugin not showing on Plugins menu (In UE_4.26)

### ISSUE THREAD

**Issue by jinhyung2003** [ruyo/VRM4U#48]
I'm currently having issue that the plugin is not visible at plugins menu in UE 4.26. I've tried both pakaged one from here and one linked with Epic Games.

**Comment by ruyo** [comment]
Hi.
I have been able to use it with 4.26.
Please refer to the following documentation to check if the files are placed correctly.

https://d3etapyazx4hzgaanfq2hik3j4--ruyo-github-io.translate.goog/VRM4U/01_quick-start/

**Comment by pmakr** [comment]
Same here not showing up

**Comment by koga6669** [comment]
its not showing up no matter where i place it i would like to see you do a up to date video of it on ue4.26 i have placed it in the said destination's and placed in other plugin files.. in-case unreal changed and no longer allow this method you provide i don't see why it wont work maybe it will show up on 4.25 if not i will assume its just a technical error due to having multiple different plugins

**Comment by ruyo** [comment]
Do you see VRM4U when you use the simple new project?
If you attach the log file, I will look into it in detail.
MyProject/Saved/Log/MyProject.log

**Comment by koga6669** [comment]
now it just says location not available my engine is in program filesx86 but when i look my plugins i can use are stored in vault so im move it there also i have projects but it does not allow me to pull any logs period

**Comment by AstrixVRchat969** [comment]
https://github.com/ruyo/VRM4U/releases

**Comment by AstrixVRchat969** [comment]
thx a lot

**Comment by jinhyung2003** [comment]
@AstrixVRchat969 

Uhh... What?
