### ISSUE TITLE
Questions on shadows on MToon shader model

### ISSUE THREAD

**Issue by jinhyung2003** [ruyo/VRM4U#66]
Hi, I'm wondering if it's possible to get shadow overlap on MToon models (sorry I don't know the term to describe this...).

![432897234897342897324](https://user-images.githubusercontent.com/19562627/114016744-1fc61380-98a6-11eb-9a4c-3a6d54a1e55d.PNG)

The left is Mtoon(Lit) and the right is SSS. Shadow doesn't affect MToon while SSS does.
I tried tweaking the material parameters for MToon but still have no clue to achieve it.

**Comment by ruyo** [comment]
Hi.
To receive shadows, we will use MToonAttachActor.

Essentially, UE4's Unlit cannot receive shadows.
VRM4U has created its own shadowmap, which allows it to receive self-shadows and shadows of objects.
You can check the shadowmap by activating the "DebugShadowCube" option.
Note that the shadows will be applied with MToon's shadow color, which is a different shade from UE4's default shadows.

Thanks.

![image](https://user-images.githubusercontent.com/6472835/114066214-70556500-98d6-11eb-94f5-8a258dbb1121.png)

**Comment by jinhyung2003** [comment]
Hi, thank you for the response. I now understand the shadowmap and the difference, but what I wanted to point out is that the MToonLit does shows the shadow, but doesn't seems to receive the object shadows a lot. I do see that object shadows overlaps the MToonLit, but it's really a small difference.

![33223432](https://user-images.githubusercontent.com/19562627/114068458-e9ee5280-98d8-11eb-954f-05cd1a167e5b.PNG)
Lit on left and unlit at right. I do see a shadow. (AO is on, no ray tracing...)

![6565654](https://user-images.githubusercontent.com/19562627/114068528-f8d50500-98d8-11eb-9bea-79972c2ebf44.PNG)
However, the MToonLit doesn't seems to receive the cylinder shadow a lot that I can feel it is recieveing.

Is it possible to "amplify" the Moonlit receiving shadows, just like how SSS receive shadows?
![897987](https://user-images.githubusercontent.com/19562627/114069571-18b8f880-98da-11eb-9c56-aa2476a41d13.PNG)

(+ sorry for asking questions a lot recently, I got a lot of interest on this plugin...)

**Comment by ruyo** [comment]
Controlling the shadows in Lit is a very tricky problem.
If you want to use dark black shadows, I suggest you use SSS materials.

The Lit in VRM4U is a composite of BaseColor and Emissive to create a color.

For example, in the attached image, the ratio is 4:1
![image](https://user-images.githubusercontent.com/6472835/114074021-e5c53380-98de-11eb-92de-809e6b53dfe8.png)


Shadows in UE4 only affect BaseColor. In other words, the color will be 80% lighter than the original shadow color.

This rate can be changed with bUseCustomBaseColorRate.
Setting this to 1 will allow you to receive a full shadow.
However, this will be the standard PBR for UE4, so the Toon atmosphere will be diminished.

If you set it to 0, it will be completely unlit and will not receive any shadows.

![image](https://user-images.githubusercontent.com/6472835/114073985-da720800-98de-11eb-82f2-de0515b98c42.png)

You can also cast darker shadows by using a stronger light.
This is because the stronger the light, the greater the effect on BaseColor.

The VRM4U Lit material is designed to look best when the DirectionalLight Intensity is set to 3.14.
If the light is extremely brighter than this, you will get darker shadows.
Of course, the Toon atmosphere will be lost.

thanks.

**Comment by jinhyung2003** [comment]
Hi,
Thanks for the answer. Since I still want to stick on Lit, I guess I'll have to give up shadow overlap I wanted, but anyway, thanks for your help.

**Comment by jinhyung2003** [comment]
Update: I controlled the basecolorrate about 0.2 and gave me this result.

![654987564](https://user-images.githubusercontent.com/19562627/114119541-d1585980-9925-11eb-8f2a-601d3d480d53.PNG)

I am pretty satisfied with this.
Thanks for info!
