### ISSUE TITLE
Basic questions and an issue with Event on landed.

### ISSUE THREAD

**Issue by workingmagic** [ruyo/VRM4U#72]
Hello Ruyo!

At the moment, I try to merge your VRM4U with another System called AGR Pro which holds a nice feature set for a lot of gameplay movement and character things. I run into a couple of question and hope you may have some ideas about.
This is the link to the youtube series from the creator: https://www.youtube.com/watch?v=ALj-vxMqCE4&list=PLTztLWdi2XEE4-MQX2BQ3i6VICXCmd42W&index=1

AGRPro (free!): https://www.unrealengine.com/marketplace/en-US/product/agr-pro

a) When I want to use VRM4U for a game, which Blueprint should be used initially? At the moment, I am using the BP_Vrm_CharacterBase. Is this correct? There is an VRMSamplePawn but I don't really understand its purpose. Which one should be used as a base?

b) Issue: Inside your second Event Graph of BR_VrmCharacterBase there is an init with a sequence. "Then 3" leads to some system which looks important, but it also breaks another custom event which is basically to play an jump-end montage with an "Event Landed". I am not sure how this could be solved, but this particular piece of BP nodes prevents it. 

This is the Event I want to add. 

![UE4Editor_z2V77K9Hhd](https://user-images.githubusercontent.com/72321604/118033000-943e1780-b368-11eb-980c-afea2ac232b0.jpg)

This is the BP part which does seems to block this simple event.

![UE4Editor_xfUVQzV9ld](https://user-images.githubusercontent.com/72321604/118032708-43c6ba00-b368-11eb-816f-3557f52b4048.jpg)

Sorry for any inconvenience, your tool is a great and I love working with it!

Kind regards,
Toby

PS: Do you have a support Discord or do you think it would make sense to setup one for people to share ideas, solve issues, showcase things build with VRM4U?

**Comment by ruyo** [comment]
Hi.
a) There is no specific Blueprint to use as a base.
As far as I can tell from the video, you can create it the same way and only replace the skeletalMesh.
The animation should be retargeted separately. If it is Humanoid compliant, you can retarget it to the VRM model.

b) When using VRMSamplePawn, you can perform animation operations on Skeletalmesh_retargetSrc.
This is a Pawn that uses runtime retargeting. It is used when you want to instantly replace multiple VRM models.
Since this is different from the standard UE4 pawn configuration, you may encounter some unexpected problems.
If you don't have a specific reason, it's better to just use skeletalMesh.

Thanks.
I don't see many VRM4U users, so I'm thinking that issues and Twitter will be enough for information sharing. If there are more, it would be good to use such tools.

**Comment by workingmagic** [comment]
Sorry for the late reply and a big thank you for answering. It helped a lot! :) Best plugin I've ever used. <3

**Comment by gostan99** [comment]
Hi, I just have a question. If I tick on generate Mipmap, do VRM4U auto use it?
