### ISSUE TITLE
A way to remove "J_Bip..." bones 

### ISSUE THREAD

**Issue by MoEmbedded** [ruyo/VRM4U#74]
Hi ruyo thanks for your hard work on this project it's really helpful for many ppl

I'm having a hard time in retargeting some animations so i decided to take the easy way and use "assign skeleton" option on the mesh to assign a  mannequin skeleton to it 
the problem with that is there is some additional bones on the vrm mannequin mesh ,so when i try to assign the editor crashes 
![skeleton](https://user-images.githubusercontent.com/78125695/119012646-80ad3500-b996-11eb-88a9-4e314270b0c9.PNG)

i tried to export the mesh as fbx to a blender BUT all the bone names are now changed 
then tried to remove the additional bones in blender export fbx and import using vrm4u as importer and checked the create renamed mesh option but now all bone names changed
![skeleton2](https://user-images.githubusercontent.com/78125695/119012668-84d95280-b996-11eb-8f08-f7c366e3b0c3.PNG)

so you know any way that might help other than exporting to blender -> deleting the unwanted bones -> renaming the bones one by one -> import normally in ue4

**Comment by ruyo** [comment]
Hi.
That's a complicated issue.

VRM4U now has the original bone names when exporting FBX. This is a bug. It will be fixed in the next version.
Only VRM import allows bone renaming, FBX import does not allow bone renaming.

Depending on the situation, assign skeleton may not work well with VRM models.
If the number of backbones differs between models, or if there is a bone with the same name in a different model, it will not work.
Also, the orientation of the bones is different from the UE4 mannequin, so even if you share the same skeleton, it will not work correctly.

VRM4U has BP_VrmPoseCopy as a workaround for this problem.
By using this, you can copy animations between VRM models.
You only need to retarget once, and you can swap VRM models thereafter.
However, if you want to attach a model or use IK, you will need to do some additional operations.

![image](https://user-images.githubusercontent.com/6472835/119174592-bab82d00-baa3-11eb-89f3-18aa94d7edd7.png)

Thanks!

**Comment by MoEmbedded** [comment]
Thanks a lot , this is really helpful 
I thought the names are the only important thing but it turned out to be as you said position ,rotation and scale must be the same  

Thank you for your support and a BIG THANK YOU for creating such amazing asset
