### ISSUE TITLE
UE 4.26 Vroid character emissive issue(?)

### ISSUE THREAD

**Issue by weloyus1989** [ruyo/VRM4U#85]
Hi ruyo, you are really awesome to develop / maintain this plugin.

I'm new to vroid and material so not sure if it is a issue.
When vroid character goes into shadow of something, it seems that she is glowing. (see picture below)
![无标题](https://user-images.githubusercontent.com/77180104/126733334-4ea31ab0-b7ba-4d60-a49a-3b1aa41f6dfc.png)
Is there anyway to make her not glowing? (Parent material of vroid in UE is really hard for me to modify)

**Comment by ruyo** [comment]
Hi.

If you simply want to reduce the brightness, you can use the LightScale parameter in the link to adjust it.

|by MToonMaterialSystem|by WBP_VRMMaterial|
|----|----|
|![image](https://user-images.githubusercontent.com/6472835/126874904-1dbaf03b-f576-4a8b-a7f2-31821539bb13.png)|![image](https://user-images.githubusercontent.com/6472835/126874909-4ddb9619-4332-4562-9c6f-988bd55aa665.png)|

To reproduce the original look of the VRM, including shadows and self-shadows of background objects, you need to use MToonAttachActor. Please refer to these links to set it up.

https://ruyo-github-io.translate.goog/VRM4U/01_look/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=ajax,elem
https://github.com/ruyo/VRM4U/issues/66

However, if you don't need to reproduce the exact look and feel of a VRM, I recommend importing it in SubsurfaceProfile mode.

Thanks

**Comment by weloyus1989** [comment]
> Hi.
> 
> If you simply want to reduce the brightness, you can use the LightScale parameter in the link to adjust it.
> 
> by MToonMaterialSystem	by WBP_VRMMaterial
> ![image](https://user-images.githubusercontent.com/6472835/126874904-1dbaf03b-f576-4a8b-a7f2-31821539bb13.png)	![image](https://user-images.githubusercontent.com/6472835/126874909-4ddb9619-4332-4562-9c6f-988bd55aa665.png)
> To reproduce the original look of the VRM, including shadows and self-shadows of background objects, you need to use MToonAttachActor. Please refer to these links to set it up.
> 
> https://ruyo-github-io.translate.goog/VRM4U/01_look/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=ajax,elem
> #66
> 
> However, if you don't need to reproduce the exact look and feel of a VRM, I recommend importing it in SubsurfaceProfile mode.
> 
> Thanks

Hello, thanks for your quick reply.
I tried your tutorial, overall light scale of character is changed. That's great.

Moreover, I have one more question, is there any method to cast (buidling/tree/etc.) shadows on character in ToonLitMode?

I also tried "Match with PBR background" tutorial, which describes main light source and skylight will affect vroid character looking. 
After adjusting materials one by one, there're still no shadows casting to character who should be darker in shadows.
However, there're some ribbonlike shiny reflections like below:
![无标题1](https://user-images.githubusercontent.com/77180104/126943870-9011f2bc-8694-4ad4-b73f-f996be4adfed.png)

Any suggestions are appreciated.
Thank you.

**Comment by ruyo** [comment]
This is due to the model data.
You are probably using AvatarSample_A. It does not have a shadow color set. Therefore, the appearance will not change.
https://hub.vroid.com/characters/2843975675147313744/models/5644550979324015604

AvatarSample_G, for example, has a shadow color set so that the back side looks slightly blue.
https://hub.vroid.com/characters/2792872861023597723/models/5013769147837660446

In VRM4U, there are two ways to adjust this.
![image](https://user-images.githubusercontent.com/6472835/127001237-d20e0325-e172-4f27-9ec6-67ac6d96bfc6.png)

1) Adjusting by global parameters.
You can use the Adjustment window or MToonMaterislSystem to adjust the shadow color and the gradient of the toon.

2) Adjusting by material.
In the Material Editor, specify the ShadeColor.

Thanks

**Comment by weloyus1989** [comment]
Thank you. It works!
